# Generated by Django 6.0.5 on 2026-05-16 22:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_apellido', models.CharField(max_length=15)),
                ('segundo_apellido', models.CharField(max_length=15, null=True)),
                ('primer_nombre', models.CharField(max_length=15)),
                ('segundo_nombre', models.CharField(max_length=15, null=True)),
                ('numero_identificacion', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='TipoCita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primer_apellido', models.CharField(max_length=15)),
                ('segundo_apellido', models.CharField(max_length=15, null=True)),
                ('primer_nombre', models.CharField(max_length=15)),
                ('segundo_nombre', models.CharField(max_length=15, null=True)),
                ('tipos_cita', models.ManyToManyField(related_name='doctores', to='agendamientoCitas.tipocita')),
            ],
        ),
        migrations.CreateModel(
            name='Cita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamientoCitas.paciente')),
                ('tipo_cita', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='agendamientoCitas.tipocita')),
            ],
        ),
    ]
