# Generated by Django 6.0.5 on 2026-05-17 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamientoCitas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.CharField(default='calle 66', max_length=200),
        ),
        migrations.AddField(
            model_name='paciente',
            name='email',
            field=models.CharField(default='prueba@hotmail.com', max_length=15),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='3159895563', max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_identificacion',
            field=models.PositiveIntegerField(default=1000898745),
        ),
    ]
