# Generated by Django 6.0.5 on 2026-05-17 04:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamientoCitas', '0002_paciente_direccion_paciente_email_paciente_telefono_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.CharField(default='prueba@hotmail.com', max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{7,15}$')], verbose_name='Teléfono'),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_identificacion',
            field=models.PositiveIntegerField(max_length=20, unique=True),
        ),
    ]
