# Generated by Django 6.0.5 on 2026-05-17 05:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamientoCitas', '0003_alter_paciente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='email',
            field=models.EmailField(default='prueba@hotmail.com', max_length=100),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_identificacion',
            field=models.PositiveIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(default='3159895563', max_length=15, validators=[django.core.validators.RegexValidator(regex='^\\+?\\d{7,15}$')]),
        ),
    ]
