# Generated by Django 6.0.5 on 2026-05-17 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamientoCitas', '0004_alter_paciente_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='segundo_apellido',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='segundo_nombre',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
