# Generated by Django 6.0.5 on 2026-05-17 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agendamientoCitas', '0005_alter_doctor_segundo_apellido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita',
            name='doctor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='agendamientoCitas.doctor'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='cita',
            unique_together={('paciente', 'tipo_cita')},
        ),
    ]
