# Generated by Django 6.0.5 on 2026-05-17 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agendamientoCitas', '0006_cita_doctor_alter_cita_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='tipos_cita',
        ),
    ]
